export const POST_PROCESSORS_JOB_OUTBOX_SUCCESS_OPTIONS =
  'POST_PROCESSORS_JOB_OUTBOX_SUCCESS_OPTIONS';
export const POST_PROCESSORS_JOB_OUTBOX_FAILURE_OPTIONS =
  'POST_PROCESSORS_JOB_OUTBOX_FAILURE_OPTIONS';
export const POST_PROCESSOR_EVENT_CREATED_OPTIONS =
  'POST_PROCESSOR_EVENT_CREATED_OPTIONS';
export const POST_PROCESSOR_USER_CREATED_OPTIONS =
  'POST_PROCESSOR_USER_CREATED_OPTIONS';
export const POST_PROCESSOR_POST_CREATED_OPTIONS =
  'POST_PROCESSOR_POST_CREATED_OPTIONS';
export const POST_PROCESSOR_POST_DELETED_OPTIONS =
  'POST_PROCESSOR_POST_DELETED_OPTIONS';
