export const POST_PROCESSORS_JOB_OUTBOX_SUCCESS_OPTIONS =
  'POST_PROCESSORS_JOB_OUTBOX_SUCCESS_OPTIONS';
export const POST_PROCESSORS_JOB_OUTBOX_FAILURE_OPTIONS =
  'POST_PROCESSORS_JOB_OUTBOX_FAILURE_OPTIONS';
