export const JOB_OUTBOX_SUCCESS_POST_PROCESSOR_OPTIONS =
  'JOB_OUTBOX_SUCCESS_POST_PROCESSOR_OPTIONS';
export const JOB_OUTBOX_FAILED_POST_PROCESSOR_OPTIONS =
  'JOB_OUTBOX_FAILED_POST_PROCESSOR_OPTIONS';
